name: Windows CI
on: [pull_request, workflow_dispatch]

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "24.11.1"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          vs-version: 16.5

      - name: Check node modules cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ./Example/0.79.6/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install node modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          cd Example/0.79.6
          yarn --pure-lockfile

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional" -y

      - name: Start Appium server
        shell: powershell
        run: |
          cd Example/0.79.6
          Start-Process PowerShell -ArgumentList "yarn appium"
