name: Windows CI
on: [pull_request, workflow_dispatch]

env:
  TEST_EXAMPLE_DIR: Example/0.62.2

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "24.11.1"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          vs-version: 16.5

      - name: Check node modules cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ./${{ env.TEST_EXAMPLE_DIR }}/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles(format('{0}/package-lock.json', env.TEST_EXAMPLE_DIR)) }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install node modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: ${{ env.TEST_EXAMPLE_DIR }}
        run: |
          npm ci

      # - name: Build x64 release
      #   working-directory: ${{ env.TEST_EXAMPLE_DIR }}
      #   run: |
      #     npx react-native run-windows --release --no-packager --no-launch --logging

      - name: Start Appium server
        shell: powershell
        working-directory: ${{ env.TEST_EXAMPLE_DIR }}
        run: |
          Start-Process PowerShell -ArgumentList "npm appium"

      - name: Run tests
        working-directory: ${{ env.TEST_EXAMPLE_DIR }}
        run: |
          npm run test:windows
